In [1]:
from scipy.spatial.transform import Rotation as R
import numpy as np

## Quaternions
in Rotation quaternions are formatted using the forth component for the scalar so
[0,0,0,1] is the identity.
you can find the documentation for Rotation at https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html

In [2]:
U =  R.from_euler("xyz", [90, 0, 0], degrees=True )

In [3]:
np.round(U.as_matrix(), decimals=2 )

array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]])

In [4]:
U.as_quat()

array([0.70710678, 0.        , 0.        , 0.70710678])

## Rotations distance

In [5]:
U1 = R.from_euler("zyx", [90, 90, 0], degrees=True )
U2 = R.from_euler("zyx", [0, 90, 90], degrees=True )


In [6]:
np.round(U1.as_matrix(), decimals=2 )

array([[ 0., -0.,  1.],
       [ 1.,  0.,  0.],
       [-0.,  1.,  0.]])

In [7]:
np.round(U1.as_quat(), decimals=2 )

array([0.5, 0.5, 0.5, 0.5])

In [8]:
np.round(U2.as_matrix(), decimals=2 )

array([[ 0.,  0.,  1.],
       [ 1.,  0., -0.],
       [-0.,  1.,  0.]])

In [9]:
np.round(U2.as_quat(), decimals=2 )

array([0.5, 0.5, 0.5, 0.5])

In [10]:
(U1.as_quat() - U2.as_quat()) @ (U1.as_quat() - U2.as_quat())

2.465190328815662e-32

In [11]:
U1 = R.from_euler("zyx", [89, 89, 0], degrees=True )
U2 = R.from_euler("zyx", [0, 89, 89], degrees=True )

In [12]:
np.round(U1.as_matrix(), decimals=2 )

array([[ 0.  , -0.02,  1.  ],
       [ 1.  ,  0.02,  0.  ],
       [-0.02,  1.  ,  0.02]])

In [13]:
np.round(U1.as_quat(), decimals=2 )

array([0.49, 0.5 , 0.5 , 0.51])

In [14]:
np.round(U2.as_matrix(), decimals=2 )

array([[ 0.02,  0.  ,  1.  ],
       [ 1.  ,  0.02, -0.02],
       [-0.02,  1.  ,  0.  ]])

In [15]:
np.round(U2.as_quat(), decimals=2 )

array([0.5 , 0.5 , 0.49, 0.51])

In [16]:
(U1.as_quat() - U2.as_quat()) @ (U1.as_quat() - U2.as_quat())

0.0001496467575757364

In [20]:
U2star = U2.as_quat()
U2star = np.array([ -x for x in U2star[:-1]] + [U2star[-1]])
np.round(U2star, decimals=2)

array([-0.5 , -0.5 , -0.49,  0.51])

In [26]:
2 * np.arccos(abs(U1.as_quat() @ U2star))

2.1349891567530017

In [28]:
np.arccos((np.trace(U1.as_matrix() @ np.transpose(U2.as_matrix())) -1)/2)

0.024466190859366563