In [106]:
from scipy.spatial.transform import Rotation as R
import numpy as np
from utils import *

## Quaternions
in Rotation quaternions are formatted using the forth component for the scalar so
[0,0,0,1] is the identity.
you can find the documentation for Rotation at https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html

In [107]:
U =  R.from_euler("xyz", [90, 0, 0], degrees=True )

In [108]:
np.round(U.as_matrix(), decimals=2 )

array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]])

In [109]:
U.as_quat()

array([0.70710678, 0.        , 0.        , 0.70710678])

## Rotations distance

very different euler angles give the same rotation and both
matrix and quaternion representation do not change

In [110]:
U1 = R.from_euler("zyx", [90, 90, 0], degrees=True )
U2 = R.from_euler("zyx", [0, 90, 90], degrees=True )


In [111]:
np.round(U1.as_matrix(), decimals=2 )

array([[ 0., -0.,  1.],
       [ 1.,  0.,  0.],
       [-0.,  1.,  0.]])

In [112]:
np.round(U1.as_quat(), decimals=2 )

array([0.5, 0.5, 0.5, 0.5])

In [113]:
np.round(U2.as_matrix(), decimals=2 )

array([[ 0.,  0.,  1.],
       [ 1.,  0., -0.],
       [-0.,  1.,  0.]])

In [114]:
np.round(U2.as_quat(), decimals=2 )

array([0.5, 0.5, 0.5, 0.5])

obviously the "distance" as squared sum of the euler angles is not an appropriate one
These are the two metrix discussed in the lecture


In [115]:
2 * np.arccos(abs(U1.as_quat() @ U2.as_quat()))

0.0

In [116]:
np.arccos((np.trace(U1.as_matrix() @ np.transpose(U2.as_matrix())) -1)/2)


0.0

Things can be more subtle with euler angles when the rotations are not the same, as they
can appear wildly different but actually be reasonably near in an appropriate metric

In [117]:
U1 = R.from_euler("zyx", [89, 89, 0], degrees=True )
U2 = R.from_euler("zyx", [0, 89, 89], degrees=True )

In [118]:
np.round(U1.as_matrix(), decimals=2 )

array([[ 0.  , -0.02,  1.  ],
       [ 1.  ,  0.02,  0.  ],
       [-0.02,  1.  ,  0.02]])

In [119]:
np.round(U1.as_quat(), decimals=2 )

array([0.49, 0.5 , 0.5 , 0.51])

In [120]:
np.round(U2.as_matrix(), decimals=2 )

array([[ 0.02,  0.  ,  1.  ],
       [ 1.  ,  0.02, -0.02],
       [-0.02,  1.  ,  0.  ]])

In [121]:
np.round(U2.as_quat(), decimals=2 )

array([0.5 , 0.5 , 0.49, 0.51])

In [122]:
2 * np.arccos(abs(U1.as_quat() @ U2.as_quat()))

0.024466190859371826

In [123]:
np.arccos((np.trace(U1.as_matrix() @ np.transpose(U2.as_matrix())) -1)/2)





0.024466190859366563

as you see the two metrics are equivalent as they both describe the arc in the 3 sphere between the 2 rotations