In [70]:
from scipy.spatial.transform import Rotation as R
import numpy as np

## Quaternions
in Rotation quaternions are formatted using the forth component for the scalar so
[0,0,0,1] is the identity.
you can find the documentation for Rotation at https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html

In [71]:
U =  R.from_euler("xyz", [90, 0, 0], degrees=True )

In [72]:
np.round(U.as_matrix(), decimals=2 )

array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]])

In [73]:
U.as_quat()

array([0.70710678, 0.        , 0.        , 0.70710678])

## Rotations distance

In [74]:
U1 = R.from_euler("zyx", [90, 90, 0], degrees=True )
U2 = R.from_euler("zyx", [0, 90, 90], degrees=True )


In [75]:
np.round(U1.as_matrix(), decimals=2 )

array([[ 0., -0.,  1.],
       [ 1.,  0.,  0.],
       [-0.,  1.,  0.]])

In [76]:
np.round(U1.as_quat(), decimals=2 )

array([0.5, 0.5, 0.5, 0.5])

In [77]:
np.round(U2.as_matrix(), decimals=2 )

array([[ 0.,  0.,  1.],
       [ 1.,  0., -0.],
       [-0.,  1.,  0.]])

In [78]:
np.round(U2.as_quat(), decimals=2 )

array([0.5, 0.5, 0.5, 0.5])

In [79]:
(U1.as_quat() - U2.as_quat()) @ (U1.as_quat() - U2.as_quat())

2.465190328815662e-32

In [80]:
U1 = R.from_euler("zyx", [89, 89, 0], degrees=True )
U2 = R.from_euler("zyx", [0, 89, 89], degrees=True )

In [81]:
np.round(U1.as_matrix(), decimals=2 )

array([[ 0.  , -0.02,  1.  ],
       [ 1.  ,  0.02,  0.  ],
       [-0.02,  1.  ,  0.02]])

In [82]:
np.round(U1.as_quat(), decimals=2 )

array([0.49, 0.5 , 0.5 , 0.51])

In [83]:
np.round(U2.as_matrix(), decimals=2 )

array([[ 0.02,  0.  ,  1.  ],
       [ 1.  ,  0.02, -0.02],
       [-0.02,  1.  ,  0.  ]])

In [84]:
np.round(U2.as_quat(), decimals=2 )

array([0.5 , 0.5 , 0.49, 0.51])

In [85]:
(U1.as_quat() - U2.as_quat()) @ (U1.as_quat() - U2.as_quat())

0.0001496467575757364